#### recap!  Indexing and conditional slicing


In [2]:
import numpy as np

In [3]:
lst = [range(20)]

In [6]:
arr = np.array(lst).reshape(4,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [13]:
arr[arr<14][3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [36]:
a = arr>5 #this returns an array
a

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [68]:
b = np.eye(4,5)
print(b)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [72]:
c= np.where(b==1,2,b)  

In [73]:
c

array([[2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 2., 0., 0.],
       [0., 0., 0., 2., 0.]])

In [76]:
d = np.linspace(0,30)
d

array([ 0.        ,  0.6122449 ,  1.2244898 ,  1.83673469,  2.44897959,
        3.06122449,  3.67346939,  4.28571429,  4.89795918,  5.51020408,
        6.12244898,  6.73469388,  7.34693878,  7.95918367,  8.57142857,
        9.18367347,  9.79591837, 10.40816327, 11.02040816, 11.63265306,
       12.24489796, 12.85714286, 13.46938776, 14.08163265, 14.69387755,
       15.30612245, 15.91836735, 16.53061224, 17.14285714, 17.75510204,
       18.36734694, 18.97959184, 19.59183673, 20.20408163, 20.81632653,
       21.42857143, 22.04081633, 22.65306122, 23.26530612, 23.87755102,
       24.48979592, 25.10204082, 25.71428571, 26.32653061, 26.93877551,
       27.55102041, 28.16326531, 28.7755102 , 29.3877551 , 30.        ])

In [77]:
d.reshape(int(d.size/2),2)

array([[ 0.        ,  0.6122449 ],
       [ 1.2244898 ,  1.83673469],
       [ 2.44897959,  3.06122449],
       [ 3.67346939,  4.28571429],
       [ 4.89795918,  5.51020408],
       [ 6.12244898,  6.73469388],
       [ 7.34693878,  7.95918367],
       [ 8.57142857,  9.18367347],
       [ 9.79591837, 10.40816327],
       [11.02040816, 11.63265306],
       [12.24489796, 12.85714286],
       [13.46938776, 14.08163265],
       [14.69387755, 15.30612245],
       [15.91836735, 16.53061224],
       [17.14285714, 17.75510204],
       [18.36734694, 18.97959184],
       [19.59183673, 20.20408163],
       [20.81632653, 21.42857143],
       [22.04081633, 22.65306122],
       [23.26530612, 23.87755102],
       [24.48979592, 25.10204082],
       [25.71428571, 26.32653061],
       [26.93877551, 27.55102041],
       [28.16326531, 28.7755102 ],
       [29.3877551 , 30.        ]])

In [79]:
np.where(d>15,d+3,d).reshape(int(d.size/2),2)

array([[ 0.        ,  0.6122449 ],
       [ 1.2244898 ,  1.83673469],
       [ 2.44897959,  3.06122449],
       [ 3.67346939,  4.28571429],
       [ 4.89795918,  5.51020408],
       [ 6.12244898,  6.73469388],
       [ 7.34693878,  7.95918367],
       [ 8.57142857,  9.18367347],
       [ 9.79591837, 10.40816327],
       [11.02040816, 11.63265306],
       [12.24489796, 12.85714286],
       [13.46938776, 14.08163265],
       [14.69387755, 18.30612245],
       [18.91836735, 19.53061224],
       [20.14285714, 20.75510204],
       [21.36734694, 21.97959184],
       [22.59183673, 23.20408163],
       [23.81632653, 24.42857143],
       [25.04081633, 25.65306122],
       [26.26530612, 26.87755102],
       [27.48979592, 28.10204082],
       [28.71428571, 29.32653061],
       [29.93877551, 30.55102041],
       [31.16326531, 31.7755102 ],
       [32.3877551 , 33.        ]])